Repository CESARBR/macaw, pull requests merged in 2020-08, with the labels that each got.

#6 m-navbar and m-navbar-item component
  src/components.d.ts
  src/components/m-header/m-header.tsx
  src/components/m-navbar-item/m-navbar-item.scss
  src/components/m-navbar-item/m-navbar-item.tsx
  src/components/m-navbar-item/readme.md
  src/components/m-navbar/m-navbar.scss
  src/components/m-navbar/m-navbar.tsx
  src/components/m-navbar/readme.md
  src/index.html
  src/styles/theme/_cesar.scss
Labels: enhancement, wip

#11 - Acrescentar propriedades de m-icon em m-button / - adicionar "regular" como type default de m-icon
  src/components/m-icon/m-icon.tsx
  src/components/m-text-field/m-text-field.tsx
Labels: bug

#10 m-navbar fixes
  src/components/m-navbar-item/readme.md
Labels: enhancement

#13 Fix for m-navbar link colors
  src/components.d.ts
  src/components/m-navbar/m-navbar.scss
Labels: bug

#14 Fix to organize <m-navbar-item> link colors
  src/components/m-navbar/m-navbar.scss
Labels: enhancement
